### ISSUE TITLE
website.models.DoesNotExist: TaskResult matching query does not exist.

### ISSUE THREAD

**Issue by todpole3** [TellinaTool/tellina_task_interface#1]
When running `make run`, one out of three times I got the following error messages instead (received every 3s):

```
[2016/12/18 07:54:24] HTTP GET /check_task_state 500 [0.04, 10.0.2.2:52612]
Internal Server Error: /check_task_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/channels/handler.py", line 228, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/tellina_task_interface/website/views.py", line 82, in check_task_state
    return HttpResponse(task_manager.check_task_state(task_id))
  File "/home/vagrant/tellina_task_interface/website/models.py", line 340, in check_task_state
    state = TaskResult.objects.filter(task_manager_id=self.id).get(task_id=task_id).state
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
website.models.DoesNotExist: TaskResult matching query does not exist.
[2016/12/18 07:54:27] HTTP GET /check_task_state 500 [0.06, 10.0.2.2:52612]
Internal Server Error: /check_task_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/channels/handler.py", line 228, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/tellina_task_interface/website/views.py", line 82, in check_task_state
    return HttpResponse(task_manager.check_task_state(task_id))
  File "/home/vagrant/tellina_task_interface/website/models.py", line 340, in check_task_state
    state = TaskResult.objects.filter(task_manager_id=self.id).get(task_id=task_id).state
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
website.models.DoesNotExist: TaskResult matching query does not exist.
[2016/12/18 07:54:30] HTTP GET /check_task_state 500 [0.05, 10.0.2.2:52612]
Internal Server Error: /check_task_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/channels/handler.py", line 228, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/tellina_task_interface/website/views.py", line 82, in check_task_state
    return HttpResponse(task_manager.check_task_state(task_id))
  File "/home/vagrant/tellina_task_interface/website/models.py", line 340, in check_task_state
    state = TaskResult.objects.filter(task_manager_id=self.id).get(task_id=task_id).state
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
website.models.DoesNotExist: TaskResult matching query does not exist.
```

When this error happens, I was able to input access code and run the rest of the demo function, but the platform cannot verify "echo 'hello world'" is the correct command.

At first glance the error seems to be saying that we forget to provide the expected task result somewhere. However, the fact that it happens non-deterministically seems to indicate that something at the system level has gone wrong.

**Comment by kvu787** [comment]
This could be caused by one of the following
* The client code is issuing a `/check_task_state` call with an invalid task_id, such as `/check_task_state?task_id=-1`.
  * Check what task_id is being sent by viewing the JS console.
  * See https://github.com/TellinaTool/tellina_task_interface/blob/master/website/static/html/task.html#L187.
* The server's database does not have an entry for that `task_id`. For example, the client requests task_id=3 but the server only has entries for task_id's 1 and 2.
  * Make sure that your `config.json` defines the tasks you want.
  * Check the task table in `db.sqlite3` and see if it has the tasks you expect.

**Comment by todpole3** [comment]
Resolved by refactoring backend logic.
