### ISSUE TITLE
Proxy server broke again after restart fix

### ISSUE THREAD

**Issue by todpole3** [TellinaTool/tellina_task_interface#15]
The proxy.log looks like below, same as what I've seen before

```
xterm -> container: f
container -> xterm: f
xterm -> container: ^M
container -> xterm: ^M

container -> xterm: css/bootstrap3/bootstrap.min.css^M
css/bootstrap3/bootstrap-glyphicons.css^M
css/bootstrap3/bootstrap.css^M
css/app.css^M
css/fonts/glyphiconshalflings-regular.svg^M
css/fonts/glyphiconshalflings-regular.eot^M
css/fonts/glyphiconshalflings-regular.ttf^M
css/fonts/glyphiconshalflings-regular.woff^M
css/fonts/glyphiconshalflings-regular.otf^M
me@5f7c5d6da8b1:~/website$
Connection from /32804
Opening websocket to ws://172.17.0.1:32804
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 172.17.0.1:32804
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm info lifecycle @~start: Failed to exec start script
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

The fix I've done for this issue are as below:
https://github.com/TellinaTool/tellina_task_interface/blob/master/Makefile#L7
https://github.com/TellinaTool/tellina_task_interface/blob/master/proxy_image/proxy_monitor.sh

I think there is a bug in my bash script because it didn't print out the error detected message when the server broke down.

**Comment by todpole3** [comment]
Fixed by c179933795dbda18b881f5c17d04b38316ac2056.
