### ISSUE TITLE
Need to update config.sample.json

### ISSUE THREAD

**Issue by kvu787** [TellinaTool/tellina_task_interface#4]
For commit: b3355a720394ae133aa366ebb9284d7dd09df70f

I get the following error when running `make run`:

```
python3 manage.py runscript load_config --traceback
Exception while running run() in 'scripts.load_config'
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runscript.py", line 165, in handle
    run_script(mod, *script_args)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runscript.py", line 77, in run_script
    mod.run(*script_args)
  File "/home/vagrant/tellina_task_interface/scripts/load_config.py", line 26, in run
    goal = task['goal']
KeyError: 'goal'
make: *** [run] Error 1
```

It looks like `config.sample.json` needs to be updated with new field names.

**Comment by todpole3** [comment]
Good call. Updated. Try it now.

**Comment by chensivan** [comment]
I think I am running into a similar error when running `make run`. Not sure how to fix this based on the previous conversation. 


```
ubuntu@ubuntu-xenial:/home/vagrant/tellina_task_interface$ make run
# Kill existing server process.
ps aux | grep npm | awk '/[ \t]/ {print }' | xargs sudo kill -9
kill: invalid argument c

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
Makefile:35: recipe for target 'clean' failed
make: [clean] Error 123 (ignored)
ps aux | grep manage.py | awk '/[ \t]/ {print }' | xargs sudo kill -9
kill: invalid argument c

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
Makefile:35: recipe for target 'clean' failed
make: [clean] Error 123 (ignored)
# Remove lock files.
ls | grep '^task_manager_lock_' | xargs rm
rm: missing operand
Try 'rm --help' for more information.
Makefile:35: recipe for target 'clean' failed
make: [clean] Error 123 (ignored)
# Delete virtual filesystems.
ls / | grep 'study_session' | xargs sudo bash delete_filesystem.bash
Makefile:35: recipe for target 'clean' failed
make: [clean] Error 123 (ignored)
# Destroy Docker containers.
sudo docker rm -f `sudo docker ps -q -a`
e3b1e2dd2232
# Destroy database migrations.
rm -rf website/migrations
# Remove container log file
rm -f container*.log
# ps aux | grep bash | awk '/[ \t]/ {print }' | xargs sudo kill -9
sudo -H pip3 install -r `pwd`/requirements.txt
Requirement already satisfied: Django==1.10.4 in /usr/local/lib/python3.5/site-packages (from -r /home/vagrant/tellina_task_interface/requirements.txt (line 1))
Requirement already satisfied: docker-py==1.10.6 in /usr/local/lib/python3.5/site-packages (from -r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: django-extensions==1.7.5 in /usr/local/lib/python3.5/site-packages (from -r /home/vagrant/tellina_task_interface/requirements.txt (line 3))
Requirement already satisfied: functions==0.7.0 in /usr/local/lib/python3.5/site-packages (from -r /home/vagrant/tellina_task_interface/requirements.txt (line 4))
Requirement already satisfied: requests!=2.11.0,>=2.5.2 in /usr/local/lib/python3.5/site-packages (from docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/local/lib/python3.5/site-packages (from docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.5/site-packages (from docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.5/site-packages (from docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py==1.10.6->-r /home/vagrant/tellina_task_interface/requirements.txt (line 2))
sudo docker build -t proxy proxy_image
Sending build context to Docker daemon  6.656kB
Step 1/4 : FROM node:4-onbuild
# Executing 5 build triggers...
Step 1/1 : ARG NODE_ENV
 ---> Using cache
Step 1/1 : ENV NODE_ENV $NODE_ENV
 ---> Using cache
Step 1/1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1/1 : RUN npm install && npm cache clean --force
 ---> Using cache
Step 1/1 : COPY . /usr/src/app
 ---> Using cache
 ---> 1ca3e127dba0
Step 2/4 : RUN apt-get update &&     apt-get install -y net-tools
 ---> Using cache
 ---> 56cbd41b0f69
Step 3/4 : EXPOSE 10412
 ---> Using cache
 ---> 0da36e29842a
Step 4/4 : CMD npm start
 ---> Using cache
 ---> 1add3aa93187
Successfully built 1add3aa93187
Successfully tagged proxy:latest
sudo docker build -t backend_container backend_container_image
Sending build context to Docker daemon  4.096kB
Step 1/6 : FROM node:4-onbuild
# Executing 5 build triggers...
Step 1/1 : ARG NODE_ENV
 ---> Using cache
Step 1/1 : ENV NODE_ENV $NODE_ENV
 ---> Using cache
Step 1/1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1/1 : RUN npm install && npm cache clean --force
 ---> Using cache
Step 1/1 : COPY . /usr/src/app
 ---> Using cache
 ---> 00ef2e2f22ee
Step 2/6 : RUN apt-get update &&     apt-get install -y vim &&     apt-get install manpages
 ---> Using cache
 ---> 0e8367490c2f
Step 3/6 : RUN useradd -ms /bin/bash me
 ---> Using cache
 ---> 26f52ab2ad93
Step 4/6 : USER me
 ---> Using cache
 ---> a622c710fc1c
Step 5/6 : EXPOSE 10411
 ---> Using cache
 ---> 77a0b904ab48
Step 6/6 : CMD npm start
 ---> Using cache
 ---> 6ca50808aa1f
Successfully built 6ca50808aa1f
Successfully tagged backend_container:latest
python3 manage.py makemigrations
No changes detected
python3 manage.py makemigrations website
Migrations for 'website':
  website/migrations/0001_initial.py:
    - Create model ActionHistory
    - Create model Container
    - Create model Researcher
    - Create model Software
    - Create model StudySession
    - Create model Task
    - Create model TaskSession
    - Create model User
    - Add field user to studysession
    - Add field task_session to actionhistory
python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, website
Running migrations:
  No migrations to apply.
# Create the example file system
tar xf data/example_website.tar.xz --overwrite --directory data/
# Start WebSocket server, restart server if end with error
bash proxy_image/proxy_monitor.sh & sleep 1
Proxy server crashed with exit code 125.  Respawning..
# Load config.json into database.
python3 manage.py runscript load_config --traceback
Proxy server crashed with exit code 125.  Respawning..
Exception while running run() in 'scripts.load_config'
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runscript.py", line 165, in handle
    run_script(mod, *script_args)
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runscript.py", line 77, in run_script
    mod.run(*script_args)
  File "/home/vagrant/tellina_task_interface/scripts/load_config.py", line 29, in run
    config = json.loads(content)
  File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Makefile:4: recipe for target 'run' failed
make: *** [run] Error 1
```
