### ISSUE TITLE
Cannot run filesystem tasks

### ISSUE THREAD

**Issue by kvu787** [TellinaTool/tellina_task_interface#7]
When I use the following config.json:

```
{
  "access_codes": [
    "bob",
    "alice"
  ],
  "task_duration_in_seconds": 30,
  "tasks": [
    {
      "task_id": "1",
      "type": "filesystem",
      "description": "Create a file named `hello.txt` in `~/dir1/dir2`.",
      "initial_filesystem": {
        "dir1": {
          "file.txt": {
            "ATTR_name": "file.txt"
          },
          "dir2": {}
        }
      },
      "goal": {
        "dir1": {
          "file.txt": {
            "ATTR_name": "file.txt"
          },
          "dir2": {
            "hello.txt": {
              "ATTR_name": "hello.txt"
            }
          }
        }
      }
    }
  ]
}
```

I get the following exception caused by `dict_2_disk`:

```
[30/Dec/2016 09:56:04] "GET /user_login?access_code=a-b&check_existing_session=true HTTP/1.1" 200 78
Internal Server Error: /a-b-study_session-1/task-1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/tellina_task_interface/website/views.py", line 52, in g
    return f(request, *args, task_session=task_session, **kwargs)
  File "/home/vagrant/tellina_task_interface/website/views.py", line 162, in get_current_task
    pathlib.Path('/{}/home'.format(container.filesystem_name)))
  File "/home/vagrant/tellina_task_interface/website/filesystem.py", line 224, in dict_2_disk
    status = dict_2_disk(subtree, path)
  File "/home/vagrant/tellina_task_interface/website/filesystem.py", line 167, in dict_2_disk
    if is_file(subtree):
  File "/home/vagrant/tellina_task_interface/website/filesystem.py", line 113, in is_file
    return list(node.keys())[0].startswith(attr_format(""))
IndexError: list index out of range
```

**Comment by todpole3** [comment]
Work around committed.

**Comment by kvu787** [comment]
This issue has resurfaced at the commit https://github.com/TellinaTool/tellina_task_interface/tree/e2f0bad4e64cf62cab9c976cbf6ed6afd773e209

with the following `config.json`:

```
{
  "access_codes": [
    "bob",
    "alice"
  ],
  "task_duration_in_seconds": 30,
  "tasks": [
    {
      "task_id": "1",
      "type": "filesystem",
      "description": "Create a file named `hello.txt` in `~/dir1/dir2`.",
      "initial_filesystem": {
        "dir1": {
          "file.txt": {
            "ATTR_name": "file.txt"
          },
          "dir2": {}
        }
      },
      "goal": {
        "dir1": {
          "file.txt": {
            "ATTR_name": "file.txt"
          },
          "dir2": {
            "hello.txt": {
              "ATTR_name": "hello.txt"
            }
          }
        }
      }
    }
  ]
}
```

**Comment by todpole3** [comment]
@kvu787 File system implementation is refactored. This should have been resolved.
